  variables:
    PROJECT_NAME: "DRace"
    GIT_SUBMODULE_STRATEGY: "normal"
  before_script:
    - echo "starting build for %PROJECT_NAME%"
  stages:
    - generate
    - validate
    - build
    - test

  cmake:
    tags:
      - windows
      - dynamorio
    stage: generate
    script:
    - echo "Release build..."
    - .\contrib\generate-ci.bat
    artifacts:
      paths:
        - build/
  compile:
    tags:
      - windows
      - dynamorio
    stage: build
    except:
      - doc-*
    script:
    - echo "Release build..."
    - .\contrib\build-ci.bat
    artifacts:
      paths:
        - build/
    dependencies:
    - cmake

  test:
    tags:
      - windows
      - dynamorio
    stage: test
    script:
    - echo "starting tests"
    - cd build; .\test\drace-tests.exe --dr 'C:\opt\DynamoRIO-Windows-7.0.17837-0\bin64\drrun.exe' --gtest_output="xml:test-results.xml"
    artifacts:
      paths:
        - build\test-results.xml
    dependencies:
    - compile

  cppcheck:
    tags:
      - windows
      - dynamorio
    stage: validate
    script:
    - cd build; C:\opt\Cppcheck\cppcheck.exe --project=compile_commands.json --enable=all --suppressions-list=suppressions.txt --output-file=cppcheck-results.xml --xml
    artifacts:
      paths:
        - build\cppcheck-results.xml
    dependencies:
    - cmake
