  variables:
    PROJECT_NAME: "DRace"
    GIT_SUBMODULE_STRATEGY: "normal"
  before_script:
    - echo "starting build for %PROJECT_NAME%"
  stages:
    - build
    - test

  build:
    tags:
      - windows
      - dynamorio
    stage: build
    script:
    - echo "Release build..."
    - .\contrib\build-ci.bat
    artifacts:
      paths:
        - build/
  test:
    tags:
      - windows
      - dynamorio
    stage: test
    script:
    - echo "starting tests"
    - cd build; .\test\drace-tests.exe --dr 'C:\opt\DynamoRIO-Windows-7.0.17837-0\bin64\drrun.exe'
    dependencies:
    - build

