.globals: &globals
  tags:
  - windows
  - dynamorio

variables:
  PROJECT_NAME: "DRace"
  GIT_SUBMODULE_STRATEGY: "normal"
before_script:
  - echo "starting build for %PROJECT_NAME%"
stages:
  - generate
  - validate
  - build
  - test

cmake:
  <<: *globals
  stage: generate
  script:
  - echo "Release build..."
  - .\contrib\generate-ci.bat
  artifacts:
    paths:
    - build-tsan-dr70
    - build-tsan-dr71
    - build-legacy-tsan-dr71
    - build-dummy
        
compile:
  <<: *globals
  stage: build
  except:
    - doc-*
  script:
  - echo "Release build..."
  - .\contrib\build-ci.bat
  artifacts:
    paths:
    - build-tsan-dr70
    - build-tsan-dr71
    - build-legacy-tsan-dr71
    - build-dummy
  dependencies:
  - cmake

cppcheck:
  <<: *globals
  stage: validate
  script:
  - cd build-tsan-dr70;  C:\opt\Cppcheck\cppcheck.exe  --project=compile_commands.json --enable=all --inline-suppr --suppressions-list=suppressions.txt --error-exitcode=1 --quiet
  - cd ../build-tsan-dr71;  C:\opt\Cppcheck\cppcheck.exe  --project=compile_commands.json --enable=all --inline-suppr --suppressions-list=suppressions.txt --error-exitcode=1 --quiet
  - cd ../build-legacy-tsan-dr71;  C:\opt\Cppcheck\cppcheck.exe  --project=compile_commands.json --enable=all --inline-suppr --suppressions-list=suppressions.txt --error-exitcode=1 --quiet
  - cd ../build-dummy; C:\opt\Cppcheck\cppcheck.exe  --project=compile_commands.json --enable=all --inline-suppr --suppressions-list=suppressions.txt --error-exitcode=1 --quiet
  dependencies:
  - cmake

#
# Test all builds
#

test-tsan-dr70:
  <<: *globals
  stage: test
  script:
  - cd build-tsan-dr70
  - echo "Use DR 7.0.x"
  - .\test\drace-tests.exe --dr 'C:\opt\DynamoRIO-Windows-7.0.17837-0\bin64\drrun.exe' --gtest_output="xml:test-results.xml"
  artifacts:
    reports:
      junit:
      - build-tsan-dr70\test-results.xml
  dependencies:
  - compile

test-tsan-dr71:
  <<: *globals
  stage: test
  script:
  - cd build-tsan-dr71
  - echo "Use DR 7.1.x"
  - .\test\drace-tests.exe --dr 'C:\opt\DynamoRIO-Windows-7.1.17963-0\bin64\drrun.exe' --gtest_output="xml:test-results.xml"
  artifacts:
    reports:
      junit:
      - build-tsan-dr71\test-results.xml
  dependencies:
  - compile

test-tsan-dr71-legacy:
  <<: *globals
  stage: test
  script:
  - cd build-legacy-tsan-dr71
  - echo "Use DR 7.1.x (LEGACY build)"
  - .\test\drace-tests.exe --dr 'C:\opt\DynamoRIO-Windows-7.1.17963-0\bin64\drrun.exe' --gtest_output="xml:test-results.xml"
  artifacts:
    reports:
      junit:
      - build-legacy-tsan-dr71\test-results.xml
  dependencies:
  - compile

